"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ProjectsService, type Project } from "@/lib/services/projects";

/* ── Types ───────────────────────────────────────────────────────────────── */
type SummaryCategory = "INTERVIEW TRANSCRIPTS" | "LITERATURE REVIEW" | "MEETING NOTES" | "CHAT SUMMARY";

interface SummaryItem {
  id: string;
  category: SummaryCategory;
  title: string;
  preview: string;
  date: string;
  tags?: string[];
}

interface ActionItem {
  id: string;
  description: string;
  assignee: string;
  deadline: string;
}

interface SummaryDetail {
  id: string;
  source: string;
  title: string;
  date: string;
  generatedIn: string;
  body: React.ReactNode;
  actionItems: ActionItem[];
}

/* ════════════════════════════════════════════════════════════════════════════
   AI Summaries Page
═══════════════════════════════════════════════════════════════════════════ */
export default function AiSummariesPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [summaries, setSummaries] = useState<SummaryItem[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const list = await ProjectsService.getAll();
        setProjects(list);
        
        // Load any saved AI chat range summaries from localStorage if available
        let saved: SummaryItem[] = [];
        try {
          saved = JSON.parse(localStorage.getItem("ai_range_summaries") || "[]");
        } catch (e) {}

        setSummaries(saved);
        if (saved.length > 0) setSelectedId(saved[0].id);
      } catch (err) {
        setSummaries([]);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  return (
    <div>
      {/* ── Privacy notice banner ─────────────────────────────────────────── */}
      <div style={s.privacyBanner}>
        <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.3" style={{ marginRight: 8, flexShrink: 0 }}>
          <rect x="1.5" y="5" width="10" height="7" rx="1" />
          <path d="M4 5V3.5a2.5 2.5 0 0 1 5 0V5" strokeLinecap="round" />
        </svg>
        All summaries are generated locally using LangChain Context Engine. Your research data is never transmitted to external servers.
      </div>

      {/* ── Page header ──────────────────────────────────────────────────── */}
      <div style={s.pageHeader}>
        <div>
          <h1 style={s.pageTitle}>AI Summaries</h1>
          <p style={s.pageSubtitle}>Review extracted insights and action items generated by LangChain.</p>
        </div>
        <Link id="btn-generate-summary" href="/dashboard/researcher/chat" style={s.generateBtn}>
          <svg width="13" height="13" viewBox="0 0 13 13" fill="currentColor" style={{ marginRight: 6 }}>
            <path d="M6.5 1l.8 2.4h2.5l-2 1.5.8 2.4-2.1-1.5-2.1 1.5.8-2.4-2-1.5h2.5z" />
            <path d="M10.5 8l.4 1.2H12l-1 .7.4 1.2-1-.7-1 .7.4-1.2-1-.7h1.2z" />
            <path d="M2.5 8l.4 1.2H4l-1 .7.4 1.2-1-.7-1 .7.4-1.2-1-.7H2.1z" />
          </svg>
          Summarize Chat Range →
        </Link>
      </div>

      {/* ── Two-column layout / Empty State ───────────────────────────────── */}
      {loading ? (
        <p style={{ color: "#888", padding: 40, textAlign: "center" }}>Loading AI summaries…</p>
      ) : summaries.length === 0 ? (
        <div style={{ padding: "60px 30px", textAlign: "center", background: "#ffffff", borderRadius: 8, border: "1px solid #e8e8e8" }}>
          <div style={{ fontSize: 36, marginBottom: 12 }}>🤖</div>
          <h3 style={{ fontSize: 16, fontWeight: 700, color: "#161616", marginBottom: 6 }}>No AI Summaries Generated Yet</h3>
          <p style={{ fontSize: 13, color: "#757575", maxWidth: 480, margin: "0 auto 20px" }}>
            Select messages in your Team Chat channels to generate instant AI range summaries and action item extractions using the LangChain Context Engine.
          </p>
          <Link href="/dashboard/researcher/chat" style={{ display: "inline-block", background: "#161616", color: "#ffffff", padding: "10px 18px", borderRadius: 6, fontSize: 13, fontWeight: 600, textDecoration: "none" }}>
            Go to Team Chat →
          </Link>
        </div>
      ) : (
        <div style={s.columns}>
          {/* Left: summary list */}
          <div style={s.listCol}>
            {summaries.map((s2) => (
              <SummaryCard
                key={s2.id}
                item={s2}
                isActive={selectedId === s2.id}
                onClick={() => setSelectedId(s2.id)}
              />
            ))}
          </div>

        {/* Right: detail panel */}
        <div style={s.detailCol}>
          {selectedId ? (
            <DetailPanel item={summaries.find((s) => s.id === selectedId) || null} />
          ) : (
            <p style={{ color: "#888", padding: 20 }}>Select a summary to view details.</p>
          )}
        </div>
      </div>
      )}
    </div>
  );
}

/* ── Summary Card ────────────────────────────────────────────────────────── */
function SummaryCard({
  item,
  isActive,
  onClick,
}: {
  item: SummaryItem;
  isActive: boolean;
  onClick: () => void;
}) {
  return (
    <button
      id={item.id}
      style={{ ...s.summaryCard, ...(isActive ? s.summaryCardActive : {}) }}
      onClick={onClick}
    >
      <div style={s.summaryCardTop}>
        <span style={s.categoryLabel}>{item.category}</span>
        <span style={s.summaryDate}>{item.date}</span>
      </div>
      <p style={s.summaryTitle}>{item.title}</p>
      <p style={s.summaryPreview}>{item.preview}</p>
      {item.tags && (
        <div style={s.tagRow}>
          {item.tags.map((t) => (
            <span key={t} style={s.tag}>{t}</span>
          ))}
        </div>
      )}
    </button>
  );
}

/* ── Detail Panel ────────────────────────────────────────────────────────── */
function DetailPanel({ item }: { item: SummaryItem | null }) {
  if (!item) {
    return <p style={{ color: "#888", padding: 20 }}>No summary selected.</p>;
  }

  return (
    <div style={s.detailCard}>
      {/* Header buttons */}
      <div style={s.detailHeadRow}>
        <button id="btn-copy-summary" style={s.actionBtn} onClick={() => navigator.clipboard.writeText(item.preview)}>
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.2" style={{ marginRight: 5 }}>
            <rect x="3.5" y="3.5" width="7" height="7" rx="1" />
            <path d="M2.5 8.5H1.5a1 1 0 0 1-1-1V1.5a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v1" />
          </svg>
          Copy
        </button>
      </div>

      {/* Source label */}
      <div style={s.detailSource}>
        <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round" style={{ marginRight: 6, flexShrink: 0 }}>
          <path d="M2 1h7l3 3v8H2V1z" />
          <path d="M9 1v3h3" />
        </svg>
        SOURCE: {item.category}
      </div>

      {/* Title */}
      <h2 style={s.detailTitle}>{item.title}</h2>

      {/* Meta */}
      <div style={s.detailMeta}>
        <span style={s.detailMetaItem}>
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.2" style={{ marginRight: 4 }}>
            <rect x="1" y="1.5" width="10" height="9.5" rx="1.2" />
            <line x1="3.5" y1="1" x2="3.5" y2="2.5" strokeLinecap="round" />
            <line x1="8.5" y1="1" x2="8.5" y2="2.5" strokeLinecap="round" />
            <line x1="1" y1="4.5" x2="11" y2="4.5" />
          </svg>
          {item.date}
        </span>
        <span style={s.detailMetaItem}>
          ⚡ Generated via LangChain Context Engine
        </span>
      </div>

      <div style={s.detailDivider} />

      {/* Body */}
      <div style={s.detailBody}>
        <p style={s.detailParagraph}>{item.preview}</p>
      </div>
    </div>
  );
}

/* ── Styles ─────────────────────────────────────────────────────────────── */
const s: Record<string, React.CSSProperties> = {
  /* Privacy banner */
  privacyBanner: {
    display: "flex",
    alignItems: "center",
    fontSize: 12,
    color: "#616161",
    background: "#ffffff",
    border: "1px solid #e0e0e0",
    borderRadius: 6,
    padding: "10px 14px",
    marginBottom: 24,
  },

  /* Page header */
  pageHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: "#161616",
    letterSpacing: "-0.5px",
    marginBottom: 4,
  },
  pageSubtitle: {
    fontSize: 13,
    color: "#9e9e9e",
  },
  generateBtn: {
    display: "flex",
    alignItems: "center",
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    color: "#161616",
    background: "#ffffff",
    border: "1px solid #d0d0d0",
    borderRadius: 6,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },

  /* Two-column layout */
  columns: {
    display: "grid",
    gridTemplateColumns: "300px 1fr",
    gap: 20,
    alignItems: "flex-start",
  },
  listCol: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
  },

  /* Summary Card */
  summaryCard: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
    padding: "14px 16px",
    background: "#ffffff",
    border: "1px solid #e0e0e0",
    borderRadius: 8,
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "border-color 0.1s",
    width: "100%",
  },
  summaryCardActive: {
    border: "1px solid #161616",
    background: "#fafafa",
  },
  summaryCardTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  categoryLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.5px",
    color: "#9e9e9e",
    textTransform: "uppercase" as const,
  },
  summaryDate: {
    fontSize: 11,
    color: "#9e9e9e",
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#161616",
    lineHeight: 1.35,
  },
  summaryPreview: {
    fontSize: 12,
    color: "#9e9e9e",
    lineHeight: 1.5,
  },
  tagRow: {
    display: "flex",
    gap: 6,
    marginTop: 4,
  },
  tag: {
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.4px",
    color: "#616161",
    background: "#f0f0f0",
    borderRadius: 3,
    padding: "2px 7px",
  },

  /* Detail panel */
  detailCol: {
    minHeight: 400,
  },
  detail: {
    background: "#ffffff",
    border: "1px solid #e0e0e0",
    borderRadius: 8,
    padding: "22px 24px",
  },
  detailSource: {
    display: "flex",
    alignItems: "center",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.6px",
    color: "#9e9e9e",
    textTransform: "uppercase" as const,
    marginBottom: 10,
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#161616",
    letterSpacing: "-0.3px",
    marginBottom: 10,
  },
  detailMeta: {
    display: "flex",
    gap: 18,
    marginBottom: 14,
  },
  detailMetaItem: {
    display: "flex",
    alignItems: "center",
    fontSize: 12,
    color: "#9e9e9e",
  },
  detailDivider: {
    height: 1,
    background: "#eeeeee",
    margin: "18px 0",
  },
  detailBody: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  detailParagraph: {
    fontSize: 13,
    color: "#424242",
    lineHeight: 1.7,
  },

  /* Action items */
  actionSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
  },
  actionHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  actionHeaderText: {
    fontSize: 14,
    fontWeight: 700,
    color: "#161616",
  },
  actionTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: 13,
    border: "1px solid #e8e8e8",
    borderRadius: 6,
    overflow: "hidden" as const,
  },
  actionTh: {
    textAlign: "left" as const,
    padding: "10px 14px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.4px",
    color: "#9e9e9e",
    textTransform: "uppercase" as const,
    background: "#fafafa",
    borderBottom: "1px solid #e8e8e8",
    whiteSpace: "nowrap" as const,
  },
  actionTr: {
    borderBottom: "1px solid #f5f5f5",
  },
  actionTd: {
    padding: "12px 14px",
    color: "#161616",
    fontSize: 13,
    verticalAlign: "middle" as const,
  },
  assigneeCell: {
    display: "flex",
    alignItems: "center",
    color: "#616161",
  },
  addKanbanBtn: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.4px",
    color: "#9e9e9e",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    whiteSpace: "nowrap" as const,
  },
};
