spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.nqmitpyrheqqrcbkwwut
spring.datasource.password=mmINekXXuCsuDloR
spring.datasource.driver-class-name=org.postgresql.Driver